config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  root 'static_pages#dashboard'
  match '/project/info', to: 'projects#info', via: 'get'
  match '/project/inspiration', to: 'projects#inspiration', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'


  resources :projects, except: [:index] do
    member do
      get 'deliverables_plan'
    end
    resources :collaborators
    resources :notes
    resources :videos
    resources :deliverables do
      resource :proof
    end

    resources :image_attachments
    resources :video_attachments
  end










end

app/models/deliverable.rb
class Deliverable < ActiveRecord::Base
  validates_presence_of :project_id, :title
  belongs_to :project
  has_many :image_attachments





end

app/controllers/deliverables_controller.rb
class DeliverablesController < ApplicationController
  before_action :find_project, except: [:index]

  def show
    @deliverable = @project.deliverables.find params[:id]
  end

  def index

  end

  def new
    @deliverable = @project.deliverables.new
  end


  def create
    @deliverable = @project.deliverables.new create_params
    if @deliverable.save
      redirect_to [@project, @deliverable], :flash => {:success => "Created new deliverable for #{@project.title}!"}
    else
      redirect_to :back, :flash => {:failure => "Something went wrong :("}
    end
  end


  def edit
    @deliverable = @project.deliverables.find params[:id]
  end

  def update
    @deliverable = @project.deliverables.find params[:id]
    if @deliverable.update_attributes create_params
      redirect_to [@project, @deliverable], :flash => {:success => "Deliverable was Successfully updated!"}
    else
      redirect_to :back, :flash => {:failure => "Something went wrong :("}
    end
  end

  def destroy
    @deliverable = @project.deliverables.find params[:id]
    if @deliverable.destroy!
      redirect_to @project, :flash => {:success => "You have successfully deleted"}
    else
      redirect_to :back, :flash => {:failure => "Something went wrong."}
    end
  end


  private

  def create_params
    params.require(:deliverable).permit(:title, :description, :timebox)
  end

  def find_project
    @project = current_user.collaborations.find(params[:project_id])
    rescue
    @project = current_user.projects.find(params[:project_id])
  end

end

app/views/deliverables/edit.html.haml
.row
  .col-md-8.col-md-offset-2
    %br
    %br
    %h1 Modify Deliverable
    %br
    %br

    = form_for([@project, @deliverable]) do |f|
      = f.label :title
      = f.text_field :title, class: "form-control"

      = f.label :description
      = f.text_area :description, rows: "6", class: "form-control"

      = f.label :timebox
      = f.date_field :timebox, :order => [:month, :day, :year], class: "form-control"

      = f.submit "Update Deliverable", class: "btn btn-default"
      %br
      %br
:javascript
  bkLib.onDomLoaded(nicEditors.allTextAreas);

app/views/deliverables/new.html.haml
.form-column
  %br
  %br
  %h1 Create Deliverable
  %br
  %br

  = form_for([@project, @deliverable]) do |f|

    = f.label :title
    = f.text_field :title, class: "form-control"

    = f.label :description
    = f.text_area :description, rows: "6", class: "form-control"

    .date-field
      = f.label :timebox
      = f.date_field :timebox, :order => [:month, :day, :year], class: "form-control"
    %br
    %br
    = f.submit "Create Deliverable"
    %br
    %br

:javascript
  bkLib.onDomLoaded(nicEditors.allTextAreas);

app/views/deliverables/show.html.haml
%head
  %link{:href => "http://fonts.googleapis.com/css?family=Questrial", :rel => "stylesheet", :type => "text/css"}
    %link{:href => "http://fonts.googleapis.com/css?family=Sanchez:400italic,400", :rel => "stylesheet", :type => "text/css"}
.smaller-column
  %br
  %a{:href => ""}
    %button.proof{:class => "pull-right"} Complete Objective

  %br
  %article.type-system-geometric
    %h1
      =@deliverable.title
      %h2.type
        ="#{(@deliverable.timebox - Date.today).numerator} days left from Goal"

    %p= simple_format(@deliverable.description)

    %br
    %a{:href => "#{project_deliverable_path(@deliverable.project_id, @deliverable)}", :method => "delete"}
      %button.danger{:class => "pull-left"} Delete
    %a{:href => "#{edit_project_deliverable_path(@deliverable.project_id, @deliverable)}"}
      %button{:class => "pull-left"} Edit