config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  root 'static_pages#dashboard'
  match '/project/info', to: 'projects#info', via: 'get'
  match '/project/inspiration', to: 'projects#inspiration', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'


  resources :projects, except: [:index] do
    member do
      get 'deliverables_plan'
    end
    resources :collaborators
    resources :notes
    resources :videos
    resources :deliverables do
      resource :proof
    end

    resources :image_attachments
    resources :video_attachments
  end










end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :find_project

  def index
    @collaborators = @project.collaborators.all
  end


  def new

  end


  def create
    email = params[:email]
    if @project.collaborate params[:email]
      redirect_to @project, :flash => {:success => "#{email} was successfully added as a collaborator!"}
    else
      redirect_to root_path, :flash => {:failure => "Something went wrong :("}
    end
  end


  def edit

  end


  def update

  end


  def destroy

  end

  private

  def find_project
    @project = current_user.projects.find params[:project_id]
  end



end

app/views/collaborators/index.html.haml
-if !@collaborators.empty?
  - @collaborators.each do |c|
    =c.email
-else
  %a{:href => "#{new_project_collaborators_path(@project)}"}
    %button Create Collaboration
%button
  %i.fa.fa-bullhorn 

app/views/collaborators/new.html.haml
.form-column
  %br
  %br
  %h1 Send Collaboration Request

  %br
  %i Use Caution... When you send a collaboration request to another user you are alowing them to make changes to your project and have access to all content. God Speed.
  %br
  %br

  .small-column
    =form_tag project_collaborators_path(@project), method: :post do
      =label_tag "User Email"
      =text_field_tag :email, nil, placeholder: "Enter Email"
      =submit_tag "Send Request"