config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  root 'static_pages#dashboard'
  match '/project/info', to: 'projects#info', via: 'get'
  match '/project/inspiration', to: 'projects#inspiration', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'


  resources :projects, except: [:index] do
    member do
      get 'deliverables_plan'
    end
    resources :collaborators
    resources :notes
    resources :videos
    resources :deliverables do
      resource :proof
    end

    resources :image_attachments
    resources :video_attachments
  end










end

app/models/project.rb
class Project < ActiveRecord::Base
  validates_presence_of :title, :deadline, :description, :client, :user_id
  belongs_to :user
  has_many :deliverables
  has_many :image_attachments
  has_many :notes
  has_many :videos
  has_many :relationships
  has_many :collaborators, through: :relationships, source: :user
  paginates_per 6


  include PgSearch
	pg_search_scope :search, against: [:title, :description],
		using: {tsearch: {dictionary: "english"}}


  def upcomming_deadlines
    self.where(deadline: (Time.now..(Time.now + 1.year)))
  end

  def has_main_image?
    main_images = image_attachments.select { |image| image.is_main? }
    !main_images.empty?
  end

  def main_image
    main_images = image_attachments.select { |image| image.is_main? }
    main_images.first.image.url
  end

  def self.ordered(params)
    order(:deadline).page params[:page]
  end

  def ratio
    completed = deliverables.select{|d| d.completed}
    "#{completed.length} / #{deliverables.length}"
  end

  def self.text_search(query)
    if query.present?
      search(query)
			#where("to_tsvector('english', book) @@ :q or to_tsvector('english', outline) @@ :q", q: query)
    else
      all
    end
  end

  def collaborate(email)
    collaborator = User.find_by(email:  email)
    self.collaborators << collaborator
  end


  def set_main_as_false
    image_attachments.each do |attachment|
      attachment.main = false
      attachment.save!
    end

  end








end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :info, :inspiration, :destroy, :edit, :update, :deliverables_plan]

  def show

  end

  def new
    @project = current_user.projects.new
  end


  def share

  end

  def create
    @project = current_user.projects.new create_params
    if @project.save!
      redirect_to @project, :flash => {:success => "Project successfully created!"}
    else
      redirect_to :back, :flash => {:failure => "Sorry. Something went wrong."}
    end
  end

  def edit

  end

  def update

    if @project.update_attributes! create_params
      redirect_to @project, :flash => {:success => "Project Successfully updated!"}
    else
      redirect_to :back, :flash => {:failure => "Sorry, somthing went wrong."}
    end
  end

  def destroy

    if @project.destroy!
      redirect_to root_path, :flash => {:success => "#{@project.title} was successfully removed!"}
    else
      redirect_to :back, :flash => {:failure => "Something went wrong."}
    end

  end

  def info

  end

  def inspiration

  end

  def deliverables_planj

  end

  private

  def create_params
    params.require(:project).permit(:title, :client, :description, :deadline, :client, :client_website_url, :client_description, :client_email)
  end

  def find_project
    @project = current_user.collaborations.find(params[:id])
    rescue
    @project = current_user.projects.find(params[:id])
  end

end

app/views/projects/deliverables_plan.html.haml
%br
%br
%br

.form-column
  %h2
    Create Deliverables
    %a.add-deliverable{:href => "#"}
      (+)
  %br
  %br

  =form_tag project_deliverables_path(@project), method: :post do

    =label_tag :title
    =text_field_tag :title

    =label_tag :timebox
    =date_field_tag :timebox

    =submit_tag "Add Deliverables"


:javascript
  $( document ).ready(function() {
    $('.add-deliverable').click(function(){
      event.preventDefault();

      $('.form-column').append( "<form accept-charset='UTF-8' action='/projects/41/deliverables' method='post'>
            <label for='title'>Title</label>
            <input id='title' name='title' type='text'>
            <label for='timebox'>Timebox</label>
            <input id='timebox' name='timebox' type='date'>
            <input name='commit' type='submit' value='Add Deliverables'>
          </form>" );
    });


  });

app/views/projects/edit.html.haml
.form-column
  %br
  %br
  %h1 Project Information
  %br
  %br

  = form_for(@project) do |f|
    = f.label :title
    = f.text_field :title

    = f.label :description
    = f.text_area :description, rows: "8"


    .date-field
      = f.label :deadline
      = f.date_field :deadline, :order => [:month, :day, :year]


    .line-behind-text
      %h6 Client Information

    = f.label :client
    = f.text_field :client

    = f.label :client_description
    = f.text_area :client_description, rows: "4"

    = f.label :client_website_url
    = f.text_field :client_website_url

    = f.label :client_email
    = f.text_field :client_email


    = f.submit "Update Project"
    %br
    %br
:javascript
  bkLib.onDomLoaded(nicEditors.allTextAreas);

app/views/projects/info.html.haml
%head
  %link{:href => "http://fonts.googleapis.com/css?family=Questrial", :rel => "stylesheet", :type => "text/css"}
    %link{:href => "http://fonts.googleapis.com/css?family=Sanchez:400italic,400", :rel => "stylesheet", :type => "text/css"}
%br
.half-column
  %article.type-system-geometric
    %p.type= "Project Deadline:  #{@project.deadline.strftime("%Y-%m-%d")}"
    %a.float-right{:href => "#{edit_project_path(@project)}"}
      %button Edit Project

    %h1
      %strong= @project.title
    %p
      = @project.description



    %h4= @project.client
    %br
    %p
      =@project.client_description

    %p
      %strong Email:
      %a{:href => "mailto:#{@project.client_email}"}= @project.client_email
    %p
      %strong Website:
      %a{:href => "http://#{@project.client_website_url}"}= @project.client_website_url

app/views/projects/inspiration.html.haml
%h1 Inspiration Page


.inspiration-column
  %button Add Video

.inspiration-column
  %button Add Image

app/views/projects/new.html.haml
.form-column
  %br
  %br
  %h1 Create new Project
  %br
  %br

  = form_for(@project) do |f|
    = f.label :title
    = f.text_field :title

    = f.label :description
    = f.text_area :description, rows: "8"


    .date-field
      = f.label :deadline
      = f.date_field :deadline, :order => [:month, :day, :year]


    .line-behind-text
      %h6 Client Information

    = f.label :client
    = f.text_field :client

    = f.label :client_description
    = f.text_area :client_description, rows: "4"

    = f.label :client_website_url
    = f.text_field :client_website_url

    = f.label :client_email
    = f.text_field :client_email


    = f.submit "Create Project"
    %br
    %br

:javascript
  bkLib.onDomLoaded(nicEditors.allTextAreas);

app/views/projects/show.html.haml
.project-wrapper-left#first
  %button.js-menu-trigger.sliding-menu-button{:type => "button"}
    %img{:alt => "Menu Icon", :src => "https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/menu.png"}
  %br


.project-wrapper-right
  %a{:href => "javascript:onApiLoad()"}
    =image_tag "drive.ico", :style => "width: 4%; height: 4%; float: right;"
  .breadcrumb
    -if !@project.image_attachments.empty?
      %a{:href => "#two"}
        %i.fa.fa-eye Inspiration
    -else
      = link_to "Upload Images!", new_project_image_attachment_path(@project)
    -if !@project.notes.empty?
      %a{:href => "#three"}
        %i.fa.fa-comments Thought Board
    -else
      = link_to "Add your thoughts to the Board!", new_project_note_path(@project)
    -if !@project.videos.empty?
      %a{:href => "#four"}
        %i.fa.fa-youtube  Video Content
    -else
      = link_to "Post Video!", new_project_video_path(@project)






  .intro-text
    %h2=strip_tags(@project.client)
    %h4=strip_tags(@project.client_description)
    %p
      =strip_tags(@project.description.truncate(200))
      %a{:href => "#{project_info_path(id: @project)}"}
        Read more
        %span »


  -if !@project.image_attachments.empty?
    .full-width#two
      .line-behind-text
        %h6 Project Inspiration

      .sample
        - @project.image_attachments.each do |attachment|

          .hover-tile-outer.modal{:style => "background-image: url(#{attachment.image.url})"}
            %label{:for => "modal-#{attachment.id}"}
              .hover-tile-container
                .hover-tile.hover-tile-visible

                .hover-tile.hover-tile-hidden
                  %h4= attachment.title
                  %p= attachment.description.truncate(200)
            %input.modal-state{:type => "checkbox", :id => "modal-#{attachment.id}"}/
            .modal-window{:style => "a{color: white;}"}
              %h3
                =link_to "View", edit_project_image_attachment_path(@project, attachment),:style => "color: white;"
              .modal-inner
                = image_tag attachment.image.url
                %label.modal-close{:for => "modal-#{attachment.id}"}


  -if !@project.notes.empty?

    .full-width#three
      .line-behind-text
        %h6 Thought Board
      .grid-items-lines
        - @project.notes.each do |note|
          %a.grid-item.modal{:href => "javascript:void(0)"}
            %label{:for => "modal-note-#{note.id}"}
              %i.fa.fa-file-text-o.fa-2x
              %br
              %br
              %h1= note.title
              %p= note.content.truncate(30)
            %input.modal-state{:type => "checkbox", :id => "modal-note-#{note.id}"}/
            .modal-window{:style => "a{color: white;}"}
              .modal-inner
                %h1= note.title
                %p= note.content
                %label.modal-close{:for => "modal-note-#{note.id}"}

        %a.grid-item{:href => "#{new_project_note_path(@project)}"}
          %i.fa.fa-plus-square.fa-4x
          %br
          %br
          %h1 Create a Note




  -if !@project.videos.empty?
    .full-width#four
      .line-behind-text
        %h6 Video Content
      -@project.videos.each do |video|
        .video
          %h2
            =video.title
            %a{:href => "#{project_video_path(@project, video)}", method: "delete",:style => "float: right; color: #d9534f;"}
              %i.fa.fa-trash
            %a{:href => "#{edit_project_video_path(@project, video)}", :style => "float: right; margin-right: .25em;"}
              %i.fa.fa-edit


          .video-wrapper
            %iframe{:allowfullscreen => "", :width => "560", :height => "315", :frameborder => "0", :src => "#{video.url}"}
        %br
        %br



%nav.js-menu.sliding-menu-content
  %br
  %br
  %h3 Objectives
  %br
  %ul
    - @project.deliverables.each do |deliverable|
      %li
        %a{:href => "#{project_deliverable_path(@project, deliverable)}"}= deliverable.title
.js-menu-screen.menu-screen