config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
  root 'static_pages#dashboard'
  match '/project/info', to: 'projects#info', via: 'get'
  match '/project/inspiration', to: 'projects#inspiration', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'


  resources :projects, except: [:index] do
    member do
      get 'deliverables_plan'
    end
    resources :collaborators
    resources :notes
    resources :videos
    resources :deliverables do
      resource :proof
    end

    resources :image_attachments
    resources :video_attachments
  end










end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Tunlvision
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %link{:href => "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    %script{:src => "https://apis.google.com/js/api.js"}


  %body
    %header.navigation
      .navigation-wrapper
        %a.logo{:href => "#{root_path}"}
          %i.fa.fa-pied-piper-alt.fa-3x
        %a#js-mobile-menu.navigation-menu-button{:href => ""} MENU
        .nav
          %ul#navigation-menu
            %li.nav-link
              %a{:href => "#{root_path}"} Projects
            -if !@project
              %li.nav-link
                =link_to "New Project", new_project_path
            -if @project && !@project.title.nil?
              %li.nav-link
                %a{:href => "#{project_path(@project)}"}
                  =@project.title
              %li.nav-link.more
                %a{:href => "javascript:void(0)"} Project Options
                %ul.submenu
                  %li
                    %a{:href => "#{project_info_path(id: @project.id)}"} Project Specifics
                  %li
                    %a{:href => "#{new_project_deliverable_path(@project)}"} New Objective
                  %li.more
                    %a{:href => "javascript:void(0)"} Add Inspiration
                    %ul.submenu
                      %li
                        %a{:href => "#{new_project_image_attachment_path(@project)}"} Image
                      %li
                        %a{:href => "#{new_project_video_path(@project)}"} Embed Video
                  %li
                    %a{:href => "#{new_project_note_path(@project)}"} Add a Note
                  %li
                    %a{:href => "#{new_project_collaborator_path(@project)}"} Create Collaboration


        .navigation-tools
          .search-bar
            .search-and-submit
              %form{:action => "/", :method => "get"}
                %input{:placeholder => "Search Project", :name => "query", :type => "search"}/
                %button{:type => "submit"}
                  %img{:alt => "Search Icon", :src => "https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/search-icon.png"}
          -if current_user
            = link_to "Sign Out", destroy_user_session_path, class: "sign-up", method: :delete
          -else
            = link_to "Sign In", new_user_session_path, class: "sign-up"


    .wrapper-for-content-outside-of-footer

      .container
        - flash.each do |key, value|
          %div{:class => "#{key}"}
            %span= value
        = yield




    .push

%footer.footer-2
  .footer-logo
    %i.fa.fa-pied-piper-alt.fa-2x
  %ul
    %li
      %a{:href => "#{about_path}"} About
    %li
      %a{:href => "#{contact_path}"} Contact
    %li
      %a{:href => "#{root_path}"} Projects
  .footer-secondary-links
    %ul
      %li
        %a{:href => "javascript:void(0)"} Terms and Conditions
      %li
        %a{:href => "javascript:void(0)"} Privacy Policy
    %ul.footer-social
      %li
        %a{:href => "javascript:void(0)"}
          %img{:alt => "Facebook", :src => "https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/facebook-logo-circle.png"}
      %li
        %a{:href => "javascript:void(0)"}
          %img{:alt => "Twitter", :src => "https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/twitter-logo-circle.png"}
      %li
        %a{:href => "javascript:void(0)"}
          %img{:alt => "YouTube", :src => "https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/youtube-logo-circle.png"}